name: Junit Integration on Java 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests --logger "xml;LogFileName=testresults.xml"
      run: mvn test
      
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always() # or you can set conditions based on your needs
      with:
        files: |
         /home/runner/work/junit5-migration-maven/junit5-migration-maven/src/test/Test reports
        

