name: Junit Integration on Java 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests 
      run: mvn test
      
    - name: Build with Maven and Save Test Results
      run: |
        mvn clean test
        mkdir -p test-results
        mv target/surefire-reports/*.xml test-results/
      # Upload test results as an artifact
    - name: Upload Test Results
      uses: actions/upload-artifact@v2
      with:
          name: test-results
          path: test-results/

        

