name: Junit Integration on Java 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'
        

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests 
      run: mvn test
      
    - name: Build with Maven and Save Test Results
      run: |
        mvn clean test
        mkdir -p test-results
        mv target/surefire-reports/*.xml test-results/
        git config --local user.email "vivek@igsindia.net"
        git config --local user.name "vivek28058"
        git add test-results
        git commit -m "Add test results" || true
        git push

        

